"""Locating and validating the Sawyer WS7 archive (tier 2 -- opt-in, but
PUBLICLY AVAILABLE: Robert J. Sawyer's own WordStar 7 archive,
https://www.sfwriter.com/ws7.htm). See tests/SAWYER-CORPUS.md for the full
account of what this tier is and why.

RULED 2026-08-26 (Jon, mid-K1-build): unlike Jon's private corpus (tested
separately, outside this repo), this repo carries an EXPLICIT, COMMITTED
list of the documents this tier tests -- never a directory sweep of the
whole archive at collection or test-run time. Revealing these
filenames/paths is explicitly fine, because the archive itself is public.

Planning #205(a), 2026-09: that committed list used to be a hand-picked
252-entry tests/sawyer_manifest.json (a "vault catalog" subset). It is now
EVERY file this engine's own detect()/parse() can classify one way or
another, and it lives directly in tests/answer_key.json (the one shared
answer key, tools/answer_key.py) -- sawyer_manifest.json is retired, its
per-doc hashes folded into that key's three groups
(convertible/known_nonconvertible/non_document_assets), each entry
carrying its own 'path' and 'source_sha256'. The classification itself is
MECHANICAL, generated by actually running core.parse() over every file in
the archive tree tools/answer_key.py --record is pointed at (see that
tool's build_sawyer()) -- never hand-curated, with exactly one deliberate
exception (NON_DOCUMENT_ASSETS, below): a WordStar-format-compatible byte
stream that nonetheless isn't a document at all (an embedded image),
identified before parsing is ever attempted, not by what parsing does
with it.

The "no directory sweep" ruling still holds at test-collection/test-run
time: sawyer_classify() below reads the committed answer_key.json only,
so it never needs the archive present, and a stranger's `pytest -m
sawyer` run against a full, untrimmed public download only ever looks at
the specific committed paths, never anything else the download also
contains. Only tools/answer_key.py --record -- a maintainer, offline,
reviewing a diff before committing it -- walks a live directory
(sawyer_enumerate_archive, below), and it is expected to be pointed at a
tree that is ALREADY the intended population (e.g. a documents-only trim),
not an arbitrary raw archive dump.

Two failure MODES at test time, and neither is a skip (2026-08-24 rule,
scoped here to "once armed"):

  1. The archive isn't there at all, or doesn't look like release 1.5 (the
     version-marker check below) -- sawyer_manifest_problem().
  2. The archive is there and looks right, but one LISTED document is
     missing or its content has drifted from the committed hash --
     sawyer_doc_problem(name).

One name, one shape, everywhere: CTRLKD_SAWYER_ARCHIVE (D3, 2026-09-03) --
the archive's own top-level directory. Its presence arms the whole
`sawyer` marker (see pyproject.toml's addopts). An earlier, now-retired
alias name is no longer honoured.
"""
import hashlib
import json
import os

ARCHIVE_ENV = 'CTRLKD_SAWYER_ARCHIVE'

# Release identity: fixed facts about which Sawyer release tests/answer_key.json
# was generated against, independent of exactly which/how-many files that
# release's tree contains (that population is recorded in answer_key.json
# itself, below) -- these only change when Sawyer ships a new release and a
# maintainer deliberately re-pins tools/answer_key.py --record against it.
# Previously lived in the now-retired tests/sawyer_manifest.json.
ARCHIVE_RELEASE = '1.5'
ARCHIVE_SOURCE_URL = 'https://www.sfwriter.com/ws7.htm'
ARCHIVE_ZIP_SHA256 = '10213b23b3d030951e093eba36a1e41cb3ea6732e8e761e1b356ba4bc902e1af'
VERSION_MARKER = {'path': 'DESCRIPT.ION',
                   'sha256': 'd90f5efdde42a06cb4a62cd1bad3fa31db7a653fe1d06ce77987085741b13675'}

_HERE = os.path.dirname(os.path.abspath(__file__))
_KEY_PATH = os.path.join(_HERE, 'answer_key.json')
with open(_KEY_PATH) as _f:
    _KEY = json.load(_f)
_SAWYER_KEY = _KEY['groups']['sawyer']

# name -> {'path', 'sha256'} for EVERY entry the archive tree can contain,
# across all three buckets -- the single place tests/conftest.py's
# require_sawyer_doc fixture and every real-document test in the suite
# resolve a name against.
SAWYER_DOCS = {
    name: {'path': entry['path'], 'sha256': entry['source_sha256']}
    for group in ('convertible', 'known_nonconvertible', 'non_document_assets')
    for name, entry in _SAWYER_KEY[group].items()
}

# The one deliberately hand-identified bucket: files that are WordStar-
# format-compatible bytes (or would otherwise be attempted) but are not a
# WordStar document at all -- an Inset-embedded image a kept document
# references (corpus README, "Document-embedded images"). Never run
# through core.parse(); source-hash-checked like everything else. See
# sawyer_is_non_document_asset() for the rule that produces this set at
# generation time -- it is recomputed there, not maintained by hand.
NON_DOCUMENT_ASSETS = frozenset(_SAWYER_KEY['non_document_assets'])

# A handful of pre-existing short aliases, kept for backward compatibility
# with tests that already reference these five documents by name (three
# duplicate -README.WS basenames disambiguated by directory, two short
# aliases handed out when the original ten-document manifest was first
# hand-built, 2026-08-24). Every other file -- including every OTHER
# duplicate basename the full corpus contains (HP-ENV.LST appears 3x,
# MAILING.DOC 2x, ...) -- is keyed by its own full path, unambiguous by
# construction. New entries are never added here; a path is always its
# own name unless it already has one of these five aliases.
_NAME_OVERRIDES = {
    '-README.WS': '-README.WS (root)',
    'APP/-README.WS': '-README.WS (APP)',
    'APP/vDosPlus/-README.WS': '-README.WS (APP/vDosPlus)',
    'ARTICLES/SCRIPT.WS': 'SCRIPT.WS',
    'INSET/PIX/WORDSTAR.PIX': 'WORDSTAR.PIX',
}


def sawyer_classify():
    """(convertible_names, known_nonconvertible_names, non_document_asset_names),
    each sorted -- the same partition tools/answer_key.py recorded into
    tests/answer_key.json's three sawyer groups. Read from that committed
    key, not the live archive -- safe to call with the archive unarmed."""
    convertible = sorted(_SAWYER_KEY['convertible'])
    nonconvertible = sorted(_SAWYER_KEY['known_nonconvertible'])
    non_document = sorted(_SAWYER_KEY['non_document_assets'])
    return convertible, nonconvertible, non_document


def sawyer_doc_name(relpath):
    """The manifest KEY for a path relative to the archive root: the path
    itself, except for the five pre-existing aliases above."""
    return _NAME_OVERRIDES.get(relpath, relpath)


def sawyer_is_non_document_asset(relpath):
    """MAINTAINER-ONLY (tools/answer_key.py --record): is this path a
    non-document asset that must never be run through core.parse() at
    all? Extension-based: every .PIX in the corpus today is exactly the
    one case (INSET/PIX/WORDSTAR.PIX, the Inset image five kept documents
    embed-reference) -- a future kept document that references a second
    embedded image would be another .PIX and correctly land here too."""
    return relpath.lower().endswith('.pix')


def sawyer_enumerate_archive(root):
    """Every FILE under `root`, as relpaths with forward slashes, sorted.

    MAINTAINER-ONLY: called by tools/answer_key.py --record against a real
    archive checkout that is ALREADY the intended population (e.g. the
    corpus's own documents-only trim), never at test-collection or
    test-run time -- see this module's docstring.

    Planning: a raw `os.walk` picks up ANY file that happens to be sitting
    in `root` at record time, tracked or not -- a stray tool-output
    artifact written beside a document (e.g. `-README.json`, a ctrl-kd
    `layout` JSON export saved into the corpus tree instead of a scratch
    directory) silently became `-README.json`, a "convertible" 390th
    document with no source, no provenance, and no place in the corpus's
    own documented kept-extensions trim -- 9 nonsense cells (a 775-page
    PDF from a JSON file) committed straight into `tests/answer_key.json`
    the next `--record` run. `root`'s maintainer copy (the corpus's own
    private git checkout -- see tests/SAWYER-CORPUS.md) is ALWAYS a git
    working tree, so `git ls-files` -- the
    checkout's own record of what actually belongs there, immune to
    whatever a later, unrelated command happens to leave lying around in
    the same directory -- is authoritative when available. A public
    stranger's own unzip of the Sawyer download (`sawyer_doc_name`'s own
    docstring: "a public user downloading the archive themselves points
    the same variable at their own unzip directory") is never a git repo,
    so this falls back to the original whole-tree walk for that case,
    unchanged."""
    try:
        import subprocess
        out = subprocess.run(
            ['git', 'ls-files', '-z'], cwd=root, check=True,
            capture_output=True).stdout.decode('utf-8', 'surrogateescape')
        tracked = sorted(p for p in out.split('\0') if p)
        if tracked:
            return tracked
    except (OSError, subprocess.CalledProcessError):
        pass
    out = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            out.append(os.path.relpath(full, root).replace(os.sep, '/'))
    return sorted(out)


def sawyer_archive():
    """The archive root directory, or None if the tier is not armed."""
    return os.environ.get(ARCHIVE_ENV) or None


def sawyer_armed():
    return sawyer_archive() is not None


def _sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def sawyer_manifest_problem():
    """The one-time sanity check: is the archive root even there, and does
    it look like release 1.5 (the version this key's hashes were computed
    against)? None if fine. Checked once per test via the
    require_sawyer_doc fixture (conftest.py) before any per-doc check --
    a stale/wrong archive should report ONE clear reason, not N confusing
    per-file mismatches."""
    root = sawyer_archive()
    if not root:
        return '%s is not set -- the sawyer tier is not armed.' % (ARCHIVE_ENV,)
    if not os.path.isdir(root):
        return '%s=%s is not a directory.' % (ARCHIVE_ENV, root)
    marker_path = os.path.join(root, VERSION_MARKER['path'])
    if not os.path.isfile(marker_path):
        return ('version marker %s not found under %s -- this does not look '
                 'like the Sawyer WS7 archive at all.' % (VERSION_MARKER['path'], root))
    got = _sha256(marker_path)
    if got != VERSION_MARKER['sha256']:
        return (
            'version marker %s does not match archive release %s '
            '(expected sha256 %s, got %s). This manifest was generated '
            'against release %s (%s) -- point %s at that release, or '
            'regenerate tests/answer_key.json against the archive you have.'
            % (VERSION_MARKER['path'], ARCHIVE_RELEASE, VERSION_MARKER['sha256'],
               got, ARCHIVE_RELEASE, ARCHIVE_SOURCE_URL, ARCHIVE_ENV))
    return None


def sawyer_doc_path(name):
    """Absolute path to a manifest-listed document. Never raises at import
    time: returns a sentinel path when unarmed so a stray direct read fails
    obviously rather than resolving somewhere unexpected."""
    root = sawyer_archive()
    rel = SAWYER_DOCS[name]['path']
    if not root:
        return os.path.join('<%s-unset>' % ARCHIVE_ENV, rel)
    return os.path.join(root, rel)


def sawyer_doc_problem(name):
    """Why a manifest-listed doc can't be used, or None if it's fine. Call
    ONLY after sawyer_manifest_problem() has returned None -- see
    require_sawyer_doc in conftest.py, which always does both in order."""
    entry = SAWYER_DOCS[name]
    path = sawyer_doc_path(name)
    if not os.path.isfile(path):
        return 'manifest doc %r (%s) not found under the archive.' % (name, entry['path'])
    got = _sha256(path)
    if got != entry['sha256']:
        return (
            'manifest doc %r (%s) does not match its committed sha256 '
            '(expected %s, got %s) -- archive content has drifted from '
            'release %s.' % (name, entry['path'], entry['sha256'], got, ARCHIVE_RELEASE))
    return None
