"""Tier 1 -- PUBLIC, always-run, zero-corpus fixtures.

K1 (three-tier test architecture), 2026-08-26: bare `pytest` in a clean
checkout must run ONLY this tier -- green, complete, ZERO skips -- because
it is the only tier that needs nothing from outside the repo. The four
`samples/*.WS` documents are public-domain texts Jon transcribed into real
WordStar files (see samples/README.md for credits); they ship IN this repo,
so there is no environment variable to arm and nothing to skip.

Since Task 3 (Engine-Test-Finalization-Plan, planning #198/#195, 2026-09),
the hash oracle these samples are checked against is tests/answer_key.json
-- the ONE shared answer key covering these 4 documents AND the Sawyer
archive's convertible documents (tests/test_sawyer_corpus.py -- the FULL
corpus, mechanically classified, since planning #205a), across
every registered format x every mode, generated by tools/answer_key.py.
This file used to carry its own narrower tests/samples_oracle.json
(tools/gen_samples_oracle.py); that file and generator are retired -- see
tools/answer_key.py's own docstring for the full schema and provenance
rationale. Every (doc, format, mode) cell is now its own named,
parametrized test, not folded into a single multi-parametrize block, so a
failure reads as "LYING.WS rtf printed" rather than a bare index.

A handful of direct content assertions ride alongside the hash gate: they
exist so a first failure reads as "the document didn't parse/convert" rather
than only ever "hash 3f8a... != 91bc...", and to give this footnote-bearing
document (LYING.WS) explicit public-fixture coverage of the note pipeline.
"""
import hashlib
import json
import os
import sys

import pytest

from ctrlkd import core, emit

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'tools'))
import answer_key as ak                                            # noqa: E402

SAMPLES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'samples')
KEY_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'answer_key.json')

KEY = json.load(open(KEY_PATH))
SAMPLES_KEY = KEY['groups']['samples']['docs']
DOCS = sorted(SAMPLES_KEY)
FORMATS = KEY['axes']['formats']
MODES = KEY['axes']['modes']

assert DOCS == ['LYING.WS', 'OCAPTAIN.WS', 'TWAINLET.WS', 'WARPRAYR.WS'], DOCS


def _doc(name):
    data = open(os.path.join(SAMPLES_DIR, name), 'rb').read()
    return core.parse(data)


# ============================================================ sanity

def test_all_four_samples_are_present_and_nonempty():
    for name in DOCS:
        path = os.path.join(SAMPLES_DIR, name)
        assert os.path.isfile(path), f'{name} missing from samples/'
        assert os.path.getsize(path) > 0, f'{name} is empty'


@pytest.mark.parametrize('name', DOCS)
def test_sample_source_hash_matches_answer_key(name):
    """The bundled fixture itself hasn't drifted from what the answer key
    was generated against (mirrors the Sawyer tier's source-hash check)."""
    data = open(os.path.join(SAMPLES_DIR, name), 'rb').read()
    digest = hashlib.sha256(data).hexdigest()
    assert digest == SAMPLES_KEY[name]['source_sha256'], (
        f'{name}: source sha256 changed -- samples/*.WS is meant to be frozen; '
        f'if this is deliberate, rerun tools/answer_key.py --record')


@pytest.mark.parametrize('name', DOCS)
def test_sample_parses_without_error(name):
    doc = _doc(name)
    assert doc.blocks, f'{name} parsed to zero blocks'


# ==================================================== answer-key grid gate
#
# One named test per (doc, format, mode) cell -- 4 docs x 6 formats x 2
# modes = 48 cases. A failure names exactly which cell changed.

CELLS = [(name, fmt, mode) for name in DOCS for fmt in FORMATS for mode in MODES]


@pytest.mark.parametrize('name,fmt,mode', CELLS,
                          ids=[f'{n}__{f}__{m}' for n, f, m in CELLS])
def test_sample_matches_answer_key(name, fmt, mode):
    doc = _doc(name)
    got = ak._cell(doc, fmt, mode)               # {'sha256', 'bytes', ['pages']}
    expected = SAMPLES_KEY[name]['cells'][f'{fmt}.{mode}']
    assert got['bytes'] == expected['bytes'], (
        f'{name} {fmt}.{mode}: output size {got["bytes"]} != committed {expected["bytes"]} '
        f'-- if this is a deliberate output change, rerun '
        f'tools/answer_key.py --record and commit the new answer key')
    assert got['sha256'] == expected['sha256'], (
        f'{name} {fmt}.{mode}: sha256 {got["sha256"]} != committed {expected["sha256"]} '
        f'-- if this is a deliberate output change, rerun '
        f'tools/answer_key.py --record and commit the new answer key')
    if fmt == 'pdf':
        assert got['pages'] == expected['pages'], (
            f'{name} {fmt}.{mode}: page count {got["pages"]} != committed {expected["pages"]}')


# ============================================= direct content assertions

def test_lying_ws_footnote_reaches_every_format():
    """LYING.WS carries a real WordStar footnote -- public-fixture coverage
    of the note pipeline, mirroring what SoftReturn's own bundled-sample
    test checks for the app."""
    doc = _doc('LYING.WS')
    assert any(n.kind == 'footnote' for n in doc.notes)
    t = emit.emit_text(doc, mode='modern')
    assert 'Did not take the prize.' in t
    h = emit.emit_html(doc, mode='modern')
    assert 'Did not take the prize.' in h
    r = emit.emit_rtf(doc, mode='modern')
    assert r'\footnote' in r or r'\chftn' in r


def test_ocaptain_ws_is_whitman_verse():
    t = emit.emit_text(_doc('OCAPTAIN.WS'), mode='modern')
    assert 'O Captain! my Captain!' in t
    assert 'Whitman' in t


def test_twainlet_ws_is_a_letter_to_whitman():
    t = emit.emit_text(_doc('TWAINLET.WS'), mode='modern')
    assert 'Whitman' in t


def test_warprayr_ws_is_the_war_prayer():
    t = emit.emit_text(_doc('WARPRAYR.WS'), mode='modern')
    assert 'The War Prayer' in t
    assert 'Mark Twain' in t
