"""Tier 1 -- PUBLIC, always-run, zero-corpus fixtures.

K1 (three-tier test architecture), 2026-08-26: bare `pytest` in a clean
checkout must run ONLY this tier -- green, complete, ZERO skips -- because
it is the only tier that needs nothing from outside the repo. The four
`samples/*.WS` documents are public-domain texts Jon transcribed into real
WordStar files (see samples/README.md for credits); they ship IN this repo,
so there is no environment variable to arm and nothing to skip.

Every document is converted across every registered format (text, markdown,
html, rtf, pdf) and both modes (printed, modern), and the result is checked
against a committed SHA-256 oracle (tests/samples_oracle.json, generated by
tools/gen_samples_oracle.py) -- a hash rather than the full text because 4
docs x 2 modes x 5 formats is a lot of bytes for what a regression test
needs, which is "did this cell's output change", not a diff view.

A handful of direct content assertions ride alongside the hash gate: they
exist so a first failure reads as "the document didn't parse/convert" rather
than only ever "hash 3f8a... != 91bc...", and to give this footnote-bearing
document (LYING.WS) explicit public-fixture coverage of the note pipeline.
"""
import hashlib
import json
import os

import pytest

from ctrlkd import core, emit
from ctrlkd.pdf import emit_pdf

SAMPLES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'samples')
ORACLE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'samples_oracle.json')

DOCS = ['LYING.WS', 'OCAPTAIN.WS', 'TWAINLET.WS', 'WARPRAYR.WS']
MODES = ['printed', 'modern']
FORMATS = ['text', 'markdown', 'html', 'rtf', 'pdf']

ORACLE = json.load(open(ORACLE_PATH))


def _doc(name):
    data = open(os.path.join(SAMPLES_DIR, name), 'rb').read()
    return core.parse(data)


def _render(doc, mode, fmt):
    if fmt == 'pdf':
        return emit_pdf(doc, mode=mode)                      # bytes
    return emit.get_emitter(fmt)['fn'](doc, mode=mode).encode('utf-8')


# ============================================================ sanity

def test_all_four_samples_are_present_and_nonempty():
    for name in DOCS:
        path = os.path.join(SAMPLES_DIR, name)
        assert os.path.isfile(path), f'{name} missing from samples/'
        assert os.path.getsize(path) > 0, f'{name} is empty'


@pytest.mark.parametrize('name', DOCS)
def test_sample_parses_without_error(name):
    doc = _doc(name)
    assert doc.blocks, f'{name} parsed to zero blocks'


# ==================================================== hash oracle gate

@pytest.mark.parametrize('name', DOCS)
@pytest.mark.parametrize('mode', MODES)
@pytest.mark.parametrize('fmt', FORMATS)
def test_sample_conversion_matches_committed_oracle(name, mode, fmt):
    doc = _doc(name)
    out = _render(doc, mode, fmt)
    digest = hashlib.sha256(out).hexdigest()
    expected = ORACLE[name][mode][fmt]
    assert len(out) == expected['size'], (
        f'{name} {mode}/{fmt}: output size {len(out)} != committed {expected["size"]} '
        f'-- if this is a deliberate output change, rerun '
        f'tools/gen_samples_oracle.py and commit the new oracle')
    assert digest == expected['sha256'], (
        f'{name} {mode}/{fmt}: sha256 {digest} != committed {expected["sha256"]} '
        f'-- if this is a deliberate output change, rerun '
        f'tools/gen_samples_oracle.py and commit the new oracle')


# ============================================= direct content assertions

def test_lying_ws_footnote_reaches_every_format():
    """LYING.WS carries a real WordStar footnote -- public-fixture coverage
    of the note pipeline, mirroring what SoftReturn's own bundled-sample
    test checks for the app."""
    doc = _doc('LYING.WS')
    assert any(n.kind == 'footnote' for n in doc.notes)
    t = emit.emit_text(doc, mode='modern')
    assert 'Did not take the prize.' in t
    h = emit.emit_html(doc, mode='modern')
    assert 'Did not take the prize.' in h
    r = emit.emit_rtf(doc, mode='modern')
    assert r'\footnote' in r or r'\chftn' in r


def test_ocaptain_ws_is_whitman_verse():
    t = emit.emit_text(_doc('OCAPTAIN.WS'), mode='modern')
    assert 'O Captain! my Captain!' in t
    assert 'Whitman' in t


def test_twainlet_ws_is_a_letter_to_whitman():
    t = emit.emit_text(_doc('TWAINLET.WS'), mode='modern')
    assert 'Whitman' in t


def test_warprayr_ws_is_the_war_prayer():
    t = emit.emit_text(_doc('WARPRAYR.WS'), mode='modern')
    assert 'The War Prayer' in t
    assert 'Mark Twain' in t
