"""Tier 2 -- EVERY file in the Sawyer archive tree this repo's own
tooling classified, not just the ten richly-tested documents in
tests/SAWYER-CORPUS.md's dedicated tests.

WHY THIS EXISTS. Planning #205(a), 2026-09-06: this used to sweep a
hand-picked 252-entry tests/sawyer_manifest.json (itself an expansion,
2026-08-26, of the original ten, taken verbatim from Jon's own vault
catalog of "genuine WordStar documents"). That manifest covered only a
subset of the corpus's own documents-only trim -- 144 more real documents
(plain-text README/reference prose, `.LST`/`.DOC` content, extensionless
`TAGS/` tag documents, and the `.PAT`/`.MRG` engine-input files WSChange
config dumps and mail-merge templates) sat in the trimmed `sawyer/` tree
un-tested simply because nobody had added them to the hand-picked list.

sawyer_manifest.json is RETIRED. `tests/answer_key.json` (tools/
answer_key.py) is now the single committed record: every file
`--record` finds under `CTRLKD_SAWYER_ARCHIVE` at generation time gets
run through this engine's real `core.detect()`/`core.parse()`, and the
result -- not a catalog, not a hand list -- decides which of three
buckets it lands in (`sawyer_fixture.sawyer_classify()`, the single
shared partition tools/answer_key.py also reads):

1. NON_DOCUMENT_ASSETS -- not a WordStar document at all. One hand-
   identified rule (`sawyer_fixture.sawyer_is_non_document_asset`): a
   `.PIX` Inset image a handful of kept documents embed-reference is
   image data, never even attempted through parse(). Source-hash-checked
   here like everything else.

2. KNOWN_NONCONVERTIBLE -- this engine's actual `core.parse()` raises on
   these, and the exact recorded reason is `str()` of that real
   exception, not a hand-typed guess -- font/cartridge width tables,
   WordPerfect-conversion keystroke data, HiJaak intermediate files, a
   search-index blob, all correctly floored to 'binary' by
   `core.detect()`'s text-density gate. Recorded as a NAMED, asserted
   fact -- each one checked to fail in exactly this way -- not silently
   excluded and not force-fed through convert() to manufacture a false
   pass. A future engine change that starts parsing one of these (e.g. a
   detect() threshold fix) is caught here as a thing that moved buckets,
   not a silent pass.

3. CONVERTIBLE -- everything else: `core.parse()` succeeds, so it gets
   the full format x mode grid, pinned by hash in `tests/answer_key.json`.

Net effect of the #205(a) expansion: sawyer coverage went from 252 total
entries (241 convertible + 10 known-nonconvertible + 1 asset) to the
corpus's full 396 (385 convertible + 10 known-nonconvertible + 1 asset).
Every file that moved from "not tested at all" to a bucket landed in
CONVERTIBLE -- the known-nonconvertible and non-document-asset sets are
byte-for-byte the same ten and one they always were; nothing that used to
convert stopped converting, and nothing new failed to parse either. See
the commit message for the full before/after counts.

ANSWER KEY (Task 3, planning #198/#195, then #205a): one named test per
(doc, format, mode) cell against `tests/answer_key.json` -- the ONE shared
key this file shares with tests/test_samples.py, generated by
tools/answer_key.py -- so a failure names exactly which cell of which
document changed, not just "the sawyer gate failed".
"""
import functools
import json
import os

import pytest

from ctrlkd import core
from ctrlkd.core import ParseError

from sawyer_fixture import (SAWYER_DOCS, sawyer_classify,
                             sawyer_doc_name, sawyer_is_non_document_asset)

import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'tools'))
import answer_key as ak                                            # noqa: E402

KEY_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'answer_key.json')
KEY = json.load(open(KEY_PATH))
SAWYER_KEY = KEY['groups']['sawyer']

ALL_NAMES = sorted(SAWYER_DOCS)
CONVERTIBLE_NAMES, NONCONVERTIBLE_NAMES, NON_DOCUMENT_NAMES = sawyer_classify()

pytestmark = pytest.mark.sawyer


# ================================================== manifest self-checks

def test_manifest_shape_matches_this_files_bookkeeping():
    """The three buckets partition ALL_NAMES exactly (every name in
    exactly one group, nothing left over), and the mechanical rule that
    decides NON_DOCUMENT_ASSETS at generation time
    (sawyer_is_non_document_asset) still agrees with what's committed --
    catches a hand-edited answer_key.json drifting from the rule that's
    supposed to produce it."""
    assert set(CONVERTIBLE_NAMES) | set(NONCONVERTIBLE_NAMES) | set(NON_DOCUMENT_NAMES) == set(ALL_NAMES)
    assert not (set(CONVERTIBLE_NAMES) & set(NONCONVERTIBLE_NAMES))
    assert not (set(CONVERTIBLE_NAMES) & set(NON_DOCUMENT_NAMES))
    assert not (set(NONCONVERTIBLE_NAMES) & set(NON_DOCUMENT_NAMES))
    for name in NON_DOCUMENT_NAMES:
        assert sawyer_is_non_document_asset(SAWYER_DOCS[name]['path']), (
            f'{name} is recorded as a non-document asset but its path no '
            f'longer matches sawyer_is_non_document_asset()')
    for name in CONVERTIBLE_NAMES + NONCONVERTIBLE_NAMES:
        assert not sawyer_is_non_document_asset(SAWYER_DOCS[name]['path']), (
            f'{name} matches sawyer_is_non_document_asset() but is not '
            f'recorded as a non-document asset')
    # name assignment round-trips through the path -- every key really is
    # sawyer_doc_name() of its own recorded path, not a stray hand edit.
    for name, entry in SAWYER_DOCS.items():
        assert sawyer_doc_name(entry['path']) == name, (name, entry['path'])


def test_dropped_v14_docs_are_confirmed_absent_not_just_unlisted():
    """DICT/-CTRL.P and DICT/TEST-ALL.WS were named in an earlier (~v1.4)
    vault catalog pass but do not exist anywhere in release 1.5's tree --
    confirmed by a full-tree search at the time, not merely absent from
    this repo's own enumeration. Documented as a standing fact: a full
    mechanical sweep of the archive (this file's whole point, since
    #205a) still finds nothing at either path."""
    dropped = {'DICT/-CTRL.P', 'DICT/TEST-ALL.WS'}
    listed_paths = {e['path'] for e in SAWYER_DOCS.values()}
    assert dropped.isdisjoint(listed_paths)


# ======================================================== (a) source hash

@pytest.mark.parametrize('name', ALL_NAMES)
def test_manifest_doc_source_hash_matches(name, require_sawyer_doc):
    """Every recorded entry, convertible or not: the archive byte content
    at its path still matches the committed sha256. This is
    require_sawyer_doc's own job (sawyer_doc_problem) -- calling it IS the
    check; a tamper/drift/missing-file failure comes from that fixture,
    loud, per tests/SAWYER-CORPUS.md."""
    path = require_sawyer_doc(name)
    assert os.path.isfile(path)


# ==================================================== (b)/(c) answer-key grid gate
#
# One parsed Document per name, shared across its 12 (format, mode) cells
# -- one parse per doc instead of one per cell, cached per test-session name.

@functools.lru_cache(maxsize=None)
def _parsed(name, path):
    data = open(path, 'rb').read()
    return core.parse(data)


FORMATS = KEY['axes']['formats']
MODES = KEY['axes']['modes']
GRID_CASES = [(name, fmt, mode) for name in CONVERTIBLE_NAMES for fmt in FORMATS for mode in MODES]


@pytest.mark.parametrize('name,fmt,mode', GRID_CASES,
                          ids=[f'{n}__{f}__{m}' for n, f, m in GRID_CASES])
def test_sawyer_doc_matches_answer_key(name, fmt, mode, require_sawyer_doc):
    """(b) parse succeeds and every registered format x mode converts
    without error; (c) each cell's sha256/byte-length matches
    tests/answer_key.json, generated from THIS engine at THIS commit
    (tools/answer_key.py)."""
    path = require_sawyer_doc(name)
    doc = _parsed(name, path)
    got = ak._cell(doc, fmt, mode)
    expected = SAWYER_KEY['convertible'][name]['cells'][f'{fmt}.{mode}']
    assert got['bytes'] == expected['bytes'], (
        f'{name} {fmt}.{mode}: output size {got["bytes"]} != committed {expected["bytes"]} '
        f'-- if deliberate, rerun tools/answer_key.py --record and commit the new answer key')
    assert got['sha256'] == expected['sha256'], (
        f'{name} {fmt}.{mode}: sha256 {got["sha256"]} != committed {expected["sha256"]} '
        f'-- if deliberate, rerun tools/answer_key.py --record and commit the new answer key')
    if fmt == 'pdf':
        assert got['pages'] == expected['pages'], (
            f'{name} {fmt}.{mode}: page count {got["pages"]} != committed {expected["pages"]}')


# ============================ named non-convertible documents (asserted)

@pytest.mark.parametrize('name', NONCONVERTIBLE_NAMES)
def test_known_nonconvertible_doc_fails_exactly_as_recorded(name, require_sawyer_doc):
    """These are real files in the archive tree that this engine's real
    core.parse() rejects -- asserted by name and by the EXACT reason
    recorded in tests/answer_key.json (str() of the real ParseError raised
    at generation time, not a hand-typed guess), so a future engine change
    that starts parsing one of these (e.g. a detect() threshold fix) is
    caught here as a thing to move into CONVERTIBLE_NAMES, not a silent
    pass."""
    path = require_sawyer_doc(name)
    data = open(path, 'rb').read()
    with pytest.raises(ParseError) as excinfo:
        core.parse(data)
    expected_reason = SAWYER_KEY['known_nonconvertible'][name]['reason']
    assert expected_reason in str(excinfo.value), (
        name, str(excinfo.value), expected_reason)


# ================================================= named non-document assets

@pytest.mark.parametrize('name', NON_DOCUMENT_NAMES)
def test_non_document_asset_is_never_run_through_parse(name, require_sawyer_doc):
    """A non-document asset (today: WORDSTAR.PIX, the Inset image five
    kept documents embed-reference) is not a WordStar document -- never
    fed to core.parse()/emit() by this suite or by tools/answer_key.py,
    only source-hash-checked like everything else. Its own recorded
    'reason' documents WHY it's excluded rather than leaving that as a
    silent omission from CONVERTIBLE_NAMES."""
    require_sawyer_doc(name)  # hash check only -- the point of this test
    assert name not in CONVERTIBLE_NAMES
    assert name not in NONCONVERTIBLE_NAMES
    assert SAWYER_KEY['non_document_assets'][name]['reason']
