"""The typestyle-number -> typeface-name table, verbatim from MicroPro's
File Format for WordStar Release 7.0 (WSFORMAT.TXT, "Typestyles are defined
by a word..." section; public copy: sfwriter.com/wsformat.txt). 245 entries,
numbers 0-244; parenthetical alternate names are the spec's own text, kept
verbatim per the pass-through rule (the consumer decides what to do with a
name -- this table never picks a font). The typestyle NUMBER is the low 9
bits of the font block's typestyle word; resolve with
TYPESTYLE_NAMES.get(style & 0x01FF)."""

TYPESTYLE_NAMES = {
    0: 'LinePrinter',
    1: 'Pica',
    2: 'Elite',
    3: 'Courier',
    4: 'Helv (also Helvetica, CG Triumvirate, and Swiss)',
    5: 'Tms Rmn (also CG Times, Times Roman and Dutch)',
    6: 'Gothic (see also 130 Letter Gothic)',
    7: 'Script',
    8: 'Prestige (see also 48 Prestige Elite)',
    9: 'Caslon',
    10: 'Orator',
    11: 'Presentations',
    12: 'Helv Cond. (also Swiss Condensed)',
    13: 'Serifa',
    14: 'Blippo',
    15: 'Windsor',
    16: 'Century (also see #23)',
    17: 'ZapfHumanist',
    18: 'Garamond',
    19: 'Cooper',
    20: 'Coronet',
    21: 'Broadway',
    22: 'Bodoni',
    23: 'Cntry Schlbk (also see #16)',
    24: 'Univ. Roman',
    25: 'Helv Outline',
    26: 'Peignot (also Exotic)',
    27: 'Clarendon',
    28: 'Stick',
    29: 'HP-GL Drafting',
    30: 'HP-GL Spline',
    31: 'Times',
    32: 'HPLJ Soft Font',
    33: 'Borders',
    34: 'Uncle Sam Open',
    35: 'Raphael',
    36: 'Uncial',
    37: 'Manhattan',
    38: 'Dom Casual',
    39: 'Old English',
    40: 'Trium Condensed',
    41: 'Trium UltraComp',
    42: 'Trade ExtraCond',
    43: 'American Classic (also Amerigo)',
    44: 'Globe Gothic Outline',
    45: 'UniversCondensed (also Zurich Condensed)',
    46: 'Univers (also Zurich)',
    47: 'TmsRmnCond (Oki Laserline 6)',
    48: 'PrstElite (see also 8 Prestige)',
    49: 'Optima',
    50: 'Aachen (Postscript)',
    51: 'AmTypewriter',
    52: 'Avant Garde',
    53: 'Benguiat',
    54: 'Brush Script',
    55: 'Carta',
    56: 'Centennial',
    57: 'Cheltenham',
    58: 'FranklinGothic',
    59: 'FrstyleScrpt',
    60: 'FrizQuadrata',
    61: 'Futura',
    62: 'Galliard',
    63: 'Glypha',
    64: 'Goudy',
    65: 'Hobo',
    66: 'LubalinGraph',
    67: 'Lucida',
    68: 'LucidaMath',
    69: 'Machine',
    70: 'Melior (also Zapf Elliptical)',
    71: 'NewBaskrvlle (also Baskerville)',
    72: 'NewCntSchlbk',
    73: 'News Gothic (also Trade Gothic)',
    74: 'Palatino (also Zapf Calligraphic)',
    75: 'Park Avenue',
    76: 'Revue',
    77: 'Sonata',
    78: 'Stencil',
    79: 'Souvenir',
    80: 'TrmpMedievel (also Activa)',
    81: 'ZapfChancery',
    82: 'ZapfDingbats',
    83: 'Stone',
    84: 'CntryOldStyle',
    85: 'Corona',
    86: 'GoudyOldStyle',
    87: 'Excelsior',
    88: 'FuturaCondensed',
    89: 'HelvCompressed',
    90: 'HelvExtraCompressed',
    91: 'Helv Narrow',
    92: 'HelvUltraCompressed',
    93: 'KorinnaKursiv',
    94: 'Lucida Sans',
    95: 'Memphis',
    96: 'Stone Informal',
    97: 'Stone Sans',
    98: 'Stone Serif',
    99: 'Postscript',
    100: 'NPS Utility',
    101: 'NPS Draft',
    102: 'NPS Corr',
    103: 'NPS SansSer Qual',
    104: 'NPS Serif Qual',
    105: 'PS Utility',
    106: 'PS Draft',
    107: 'PS Corr',
    108: 'PS SansSer Qual',
    109: 'PS Serif Qual',
    110: 'Download',
    111: 'NPS ECS Qual (daisy wheel)',
    112: 'PS Plastic (daisy wheel)',
    113: 'PS Metal (daisy wheel)',
    114: 'CloisterBlack',
    115: 'Gill Sans (also Hammersmith)',
    116: 'Rockwell (also Slate)',
    117: 'Tiffany (ITC)',
    118: 'Clearface',
    119: 'Amelia',
    120: 'HandelGothic',
    121: 'OratorSC (Star et al)',
    122: 'Outline (Toshiba)',
    123: 'Bookman Light (Canon)',
    124: 'Humanist (Canon)',
    125: 'Swiss Narrow (Canon)',
    126: 'ZapfCalligraphic (Canon)',
    127: 'Spreadsheet (Quadlaser)',
    128: 'Broughm (Brother printers)',
    129: 'Anelia (Brother printers)',
    130: 'LtrGothic (as defined by Brother)',
    131: 'Boldface (Boldface PS)',
    132: 'High Density (NEC)',
    133: 'High Speed (NEC)',
    134: 'Super Focus (NEC P2200)',
    135: 'Swiss Outline (Cordata)',
    136: 'Swiss Display (Cordata)',
    137: 'Momento Outline (Cordata)',
    138: 'Courier Italic (TI 855)',
    139: 'Text Light (Cordata)',
    140: 'Momento Heavy (Cordata)',
    141: 'BarCode',
    142: 'EAN/UPC',
    143: 'Math-7 (HPLJ)',
    144: 'Math-8 (HPLJ)',
    145: 'Swiss',
    146: 'Dutch',
    147: 'Trend (Nissho)',
    148: 'Holsatia (Qume Laser)',
    149: 'Serif (IBM Pageprinter)',
    150: 'Bandit (Cordata)',
    151: 'Bookman (Cordata)',
    152: 'Casual (Cordata)',
    153: 'Dot (Cordata)',
    154: 'EDP (Epson GQ3500)',
    155: 'ExtGraphics (Epson GQ3500)',
    156: 'Garland (Canon Laser)',
    157: 'PC Line',
    158: 'HP Line',
    159: 'Hamilton (QMS)',
    160: 'Korinna (Cordata)',
    161: 'LineDrw (QMS)',
    162: 'Modern',
    163: 'Momento (Cordata)',
    164: 'MX (Cordata)',
    165: 'PC (Cordata)',
    166: 'PI',
    167: 'Profile (Quadlaser)',
    168: 'Q-Fmt (QMS)',
    169: 'Rule (Cordata)',
    170: 'SB (Cordata)',
    171: 'Taylor (Cordata)',
    172: 'Text (Cordata)',
    173: 'APL',
    174: 'Artisan',
    175: 'Triumvirate',
    176: 'Chart',
    177: 'Classic',
    178: 'Data',
    179: 'Document',
    180: 'Emperor',
    181: 'Essay',
    182: 'Forms',
    183: 'Facet',
    184: 'Micro (also Microstyle, Eurostyle)',
    185: 'OCR-A',
    186: 'OCR-B',
    187: 'Apollo (Blaser)',
    188: 'Math',
    189: 'Scientific',
    190: 'Sonoran (IBM Pageprinter)',
    191: 'Square 3',
    192: 'Symbol',
    193: 'Tempora',
    194: 'Title',
    195: 'Titan',
    196: 'Theme',
    197: 'TaxLineDraw',
    198: 'Vintage',
    199: 'XCP',
    200: 'Eletto (Olivetti)',
    201: 'Est Elite (Olivetti)',
    202: 'Idea (Olivetti)',
    203: 'Italico (Olivetti)',
    204: 'Kent (Olivetti)',
    205: 'Mikron (Olivetti)',
    206: 'Notizia (Olivetti)',
    207: 'Roma (Olivetti)',
    208: 'Presentor (Olivetti)',
    209: 'Victoria (Olivetti)',
    210: 'Draft Italic (Olivetti)',
    211: 'PS Capita (Olivetti)',
    212: 'Qual Italic (Olivetti)',
    213: 'Antique Olive (also Provence)',
    214: 'Bauhaus (ITC)',
    215: 'Eras (ITC)',
    216: 'Mincho',
    217: 'SerifGothic (ITC)',
    218: 'Signet Roundhand',
    219: 'Souvenir Gothic',
    220: 'Stymie (ATF)',
    221: 'Bernhard Modern',
    222: 'Grand Ronde Script',
    223: 'Ondine (also Mermaid)',
    224: 'PT Barnum',
    225: 'Kaufmann',
    226: 'Bolt (ITC)',
    227: 'AntOliveCompact (also Provence Compact)',
    228: 'Garth Graphic',
    229: 'Ronda (ITC)',
    230: 'EngShcreibschrift',
    231: 'Flash',
    232: 'Gothic Outline (URW)',
    233: 'Akzidenz-Grotesk',
    234: 'TD Logos',
    235: 'Shannon',
    236: 'Oberon',
    237: 'Callisto',
    238: 'Charter',
    239: 'Plantin',
    240: 'Helvetica Black (PS)',
    241: 'Helvetica Light (PS)',
    242: 'Arnold Bocklin (PS)',
    243: 'Fette Fraktur (PS)',
    244: 'Greek (PS (Universal Greek))',
}
