#!/usr/bin/env python3
"""Regenerate tests/answer_key.json -- the ONE shared answer key.

WHY THIS EXISTS (planning #198/#195, Engine-Test-Finalization-Plan Task 3)
----------------------------------------------------------------------------
Before this file, ctrl-kd carried TWO separate self-recorded oracles
(tests/samples_oracle.json for the 4 bundled samples, tests/sawyer_oracle.json
for the Sawyer archive's 241 convertible documents), each covering a
different, narrower slice of formats/modes, generated by two near-duplicate
scripts (tools/gen_samples_oracle.py, tools/gen_sawyer_oracle.py). This file
replaces both: every PUBLIC document (the 4 bundled samples + all 252 Sawyer
manifest entries) x every registered export format x every mode this engine
actually supports, in one place, with the exact options and provenance
recorded alongside the hashes.

This is a SELF-RECORDED oracle, same honesty class as its two predecessors
(see tests/SAWYER-CORPUS.md and the Test-Truth-Audit): it detects DRIFT in
this engine's own output over time, not correctness against real WordStar 7.
That external-truth comparison is a separate tier (`pcl`, tools/pcl_tolerance.py)
over a private corpus with real WS7 LaserJet captures -- this file's job is
narrower and stated plainly: "did this cell's output change since it was last
reviewed."

SCOPE. ctrl-kd's own registered formats (see ctrlkd.emit.formats(), plus
`pdf` registered separately in ctrlkd.pdf): text, markdown, html, rtf, pdf,
layout -- SIX formats. `txt`/`md` are aliases of `text`/`markdown`, not
separate cells. There is no DOCX emitter in this repo (DOCX is a Swift/`sr`
and macOS-app-side format only) -- DOCX cells belong to that repo's own
overlay, not here. ctrl-kd has exactly TWO modes, `printed` and `modern`
(`--mode` in cli.py); "native" is a Swift/app-side view concept with no
counterpart in this library -- there is no third mode to enumerate here.

Two format/mode combinations are worth naming explicitly rather than
silently recording twice: `layout`'s `mode=` PARAMETER IS ACCEPTED BUT
IGNORED (ctrlkd/layout.py's emit_layout always returns BOTH `printed` and
`modern` views in one JSON document, regardless of what `mode` is passed) --
so `layout.printed` and `layout.modern` are byte-identical for every
document, by design, not a bug in this generator. Likewise a `printstream`/
`columnar` document (WS4 print-to-disk captures, ruler-driven tables) is
silently rendered as printed regardless of the requested mode (every
non-pdf emit_* computes `printed = mode == 'printed' or _printed(doc)`) --
for those documents every `<fmt>.modern` cell equals its `<fmt>.printed`
cell too. Both are recorded anyway (the grid stays a uniform cross product,
which is what makes "docs x formats x modes" arithmetic checkable at a
glance) -- a future engine change that makes either of these actually vary
by mode will show up here as a diff to review, which is exactly the point
of a self-recorded oracle.

OPTIONS. Every cell is rendered as `<emitter-fn>(doc, mode=mode)` -- ZERO
additional keyword arguments -- i.e. every option each emitter accepts
(notes, styles, fonts_target, note_refs, headers, toc, sentence_spacing,
page_settings, ...) is left at that emitter's own library default. This is
the same discipline tools/gen_samples_oracle.py and tools/gen_sawyer_oracle.py
already followed; it is NOT the same invocation the private repo's
macos/scripts/generate_oracle_manifest.py uses for its own cross-engine
manifest (that script passes `--fonts mac` via the CLI, matching `sr`'s own
default per the D7 ruling) -- that is a DIFFERENT file for a DIFFERENT
purpose (cross-engine parity, not this engine's own drift detection), read
read-only for its cell-key convention (`"<fmt>.<mode>"`) and format/mode
list, reused here because they are already the right list, not because the
two files need to share option choices.

PROVENANCE, DETERMINISTICALLY. "generator" records the current commit
(`git rev-parse HEAD` at generation time) and that commit's own date
(`git log -1 --format=%cI`) -- NOT wall-clock `datetime.now()`. A literal
timestamp would make "generate twice and diff" (the determinism check this
file's docstring promises) fail across a day boundary for a no-op rerun;
anchoring "date" to HEAD's own commit date instead means two runs against
the same commit always produce byte-identical output, and the recorded date
still means something (when the engine that produced this key was last
committed), consistent with "regeneration is a reviewed diff, checked in
alongside the commit that motivated it."

NEGATIVES. Sawyer entries this engine's real core.parse() rejects get their
recorded failure reason, not a format/mode grid -- core.parse() itself
raises before any emitter would run. The one NON_DOCUMENT_ASSET (an Inset
image a handful of kept documents embed-reference, never a WordStar
document itself) is recorded with its own reason and is never run through
parse() either. Both sets, plus the convertible set, are the single
sawyer_fixture.sawyer_classify() partition -- tests/test_sawyer_corpus.py
reads the exact same partition, so the two can't silently drift apart.

FULL-CORPUS COVERAGE (planning #205a, 2026-09-06). This file originally
covered the 4 bundled samples plus a hand-picked 252-entry
tests/sawyer_manifest.json subset of the Sawyer archive (241 convertible +
10 known-nonconvertible + 1 asset). build_sawyer() now walks EVERY file
under CTRLKD_SAWYER_ARCHIVE at generation time
(sawyer_fixture.sawyer_enumerate_archive) and classifies each one the same
mechanical way -- run it through detect()/parse() and record what actually
happens -- so every file in the archive tree this variable is pointed at
ends up in exactly one of the three groups, not just the previously
hand-picked subset. sawyer_manifest.json is retired: its per-doc hashes
are now this key's own 'source_sha256' fields, one per entry, in whichever
group that entry landed in. A maintainer running --record is expected to
point CTRLKD_SAWYER_ARCHIVE at a tree that is ALREADY the intended
population (this project's own documents-only trim of the archive, not an
arbitrary raw download) -- see tests/SAWYER-CORPUS.md.

USAGE
    CTRLKD_SAWYER_ARCHIVE=/path/to/WS python3 tools/answer_key.py --record
    CTRLKD_SAWYER_ARCHIVE=/path/to/WS python3 tools/answer_key.py --check

Never run from inside a test -- a change to this file is a reviewed diff,
never a side effect of `pytest`.
"""
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'src'))
sys.path.insert(0, os.path.join(ROOT, 'tests'))

from ctrlkd import core, emit                                     # noqa: E402
from ctrlkd.pdf import emit_pdf                                   # noqa: E402
from ctrlkd import __version__ as ENGINE_VERSION                  # noqa: E402
from sawyer_fixture import (sawyer_manifest_problem, sawyer_archive,  # noqa: E402
                             sawyer_enumerate_archive, sawyer_doc_name,
                             sawyer_is_non_document_asset, ARCHIVE_RELEASE)

KEY_PATH = os.path.join(ROOT, 'tests', 'answer_key.json')
SAMPLES_DIR = os.path.join(ROOT, 'samples')
SAMPLE_DOCS = ['LYING.WS', 'OCAPTAIN.WS', 'TWAINLET.WS', 'WARPRAYR.WS']

FORMATS = ['text', 'markdown', 'html', 'rtf', 'pdf', 'layout']
MODES = ['printed', 'modern']

_PDF_PAGE_COUNT_RE = re.compile(rb'/Type\s*/Pages\s*/Kids\s*\[[^\]]*\]\s*/Count\s+(\d+)')


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def _pdf_page_count(data):
    m = _PDF_PAGE_COUNT_RE.search(data)
    if not m:
        raise ValueError(
            "could not find '/Type /Pages ... /Count N' in generated PDF -- "
            "ctrlkd/pdf.py's page-tree object shape changed; update this regex")
    return int(m.group(1))


def _cell(doc, fmt, mode):
    if fmt == 'pdf':
        data = emit_pdf(doc, mode=mode)
    else:
        data = emit.get_emitter(fmt)['fn'](doc, mode=mode).encode('utf-8')
    entry = {'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)}
    if fmt == 'pdf':
        entry['pages'] = _pdf_page_count(data)
    return entry


def _grid(doc):
    return {f'{fmt}.{mode}': _cell(doc, fmt, mode) for fmt in FORMATS for mode in MODES}


def _git_generator():
    sha = subprocess.check_output(['git', '-C', ROOT, 'rev-parse', 'HEAD'],
                                   text=True).strip()
    date = subprocess.check_output(['git', '-C', ROOT, 'log', '-1', '--format=%cI', 'HEAD'],
                                    text=True).strip()
    dirty = subprocess.run(['git', '-C', ROOT, 'diff', '--quiet', 'HEAD', '--',
                             'src/'], check=False).returncode != 0
    return sha, date, dirty


def build_samples():
    docs = {}
    for name in SAMPLE_DOCS:
        path = os.path.join(SAMPLES_DIR, name)
        data = open(path, 'rb').read()
        doc = core.parse(data)
        docs[name] = {
            'source_sha256': hashlib.sha256(data).hexdigest(),
            'cells': _grid(doc),
        }
    return docs


def build_sawyer():
    """Walk the ENTIRE tree at CTRLKD_SAWYER_ARCHIVE (expected to already be
    the intended population -- e.g. the corpus's own documents-only trim,
    never an arbitrary raw archive dump) and mechanically classify every
    file it contains, via this engine's real detect()/parse(), into
    exactly one of three buckets. Nothing is hand-curated except
    sawyer_is_non_document_asset()'s rule (one file today: the Inset image
    a handful of kept documents embed-reference) -- everything else is
    "what actually happens when you run it," recorded, not decided."""
    root = sawyer_archive()
    convertible = {}
    known_nonconvertible = {}
    non_document_assets = {}
    for rel in sawyer_enumerate_archive(root):
        name = sawyer_doc_name(rel)
        data = open(os.path.join(root, rel), 'rb').read()
        sha = hashlib.sha256(data).hexdigest()
        if sawyer_is_non_document_asset(rel):
            non_document_assets[name] = {
                'path': rel,
                'source_sha256': sha,
                'reason': 'not a WordStar document (Inset image asset) -- '
                          'source-hash-checked only, never run through parse()',
            }
            continue
        try:
            doc = core.parse(data)
        except core.ParseError as e:
            known_nonconvertible[name] = {
                'path': rel, 'source_sha256': sha, 'reason': str(e)}
            continue
        convertible[name] = {
            'path': rel, 'source_sha256': sha, 'cells': _grid(doc)}
    return convertible, known_nonconvertible, non_document_assets, len(convertible)


def build():
    problem = sawyer_manifest_problem()
    if problem:
        raise SystemExit(
            'archive not armed/correct: %s\n'
            'set CTRLKD_SAWYER_ARCHIVE to the Sawyer WS7 archive root.' % problem)

    sha, date, src_dirty = _git_generator()
    if src_dirty:
        print('warning: src/ has uncommitted changes -- recorded git_sha will not '
              'match the engine that actually produced these cells', file=sys.stderr)

    samples_docs = build_samples()
    sawyer_docs, known_nonconvertible, non_document_assets, n_convertible = build_sawyer()

    n_samples = len(samples_docs)
    n_formats = len(FORMATS)
    n_modes = len(MODES)
    cells_per_doc = n_formats * n_modes
    total_convertible_docs = n_samples + n_convertible
    total_grid_cells = total_convertible_docs * cells_per_doc

    key = {
        'schema_version': 1,
        'generator': {'tool': 'tools/answer_key.py', 'git_sha': sha, 'date': date},
        'engine_version': ENGINE_VERSION,
        'axes': {'formats': FORMATS, 'modes': MODES},
        'options': ('every cell is <emitter>(doc, mode=mode) with zero additional '
                    'keyword arguments -- every other option (notes, styles, '
                    'fonts_target, note_refs, headers, toc, sentence_spacing, '
                    'page_settings, ...) is that emitter\'s own library default'),
        'groups': {
            'samples': {
                'source': 'bundled samples/*.WS (public-domain texts, in-repo, see samples/README.md)',
                'docs': samples_docs,
            },
            'sawyer': {
                'source': "Robert J. Sawyer's public WS7 archive, release %s "
                          "(tests/SAWYER-CORPUS.md) -- every file under "
                          "CTRLKD_SAWYER_ARCHIVE at generation time, mechanically "
                          "classified via this engine's own detect()/parse()" % ARCHIVE_RELEASE,
                'convertible': sawyer_docs,
                'known_nonconvertible': known_nonconvertible,
                'non_document_assets': non_document_assets,
            },
        },
        'counts': {
            'samples_docs': n_samples,
            'sawyer_total_docs': (n_convertible + len(known_nonconvertible)
                                   + len(non_document_assets)),
            'sawyer_convertible_docs': n_convertible,
            'sawyer_known_nonconvertible': len(known_nonconvertible),
            'sawyer_non_document_assets': len(non_document_assets),
            'total_convertible_docs': total_convertible_docs,
            'formats': n_formats,
            'modes': n_modes,
            'cells_per_doc': cells_per_doc,
            'total_grid_cells': total_grid_cells,
            'arithmetic': ('(%d samples + %d sawyer convertible) docs x %d formats x '
                            '%d modes = %d docs x %d cells/doc = %d grid cells'
                            % (n_samples, n_convertible, n_formats, n_modes,
                               total_convertible_docs, cells_per_doc, total_grid_cells)),
        },
    }
    return key


def main():
    if '--record' not in sys.argv and '--check' not in sys.argv:
        print(__doc__)
        return 2
    fresh = build()
    if '--check' in sys.argv:
        if not os.path.exists(KEY_PATH):
            print('no existing answer key to check against'); return 1
        current = json.load(open(KEY_PATH))
        if current != fresh:
            print('tests/answer_key.json is STALE -- rerun with --record')
            return 1
        print('tests/answer_key.json matches current engine output (%s)'
              % fresh['counts']['arithmetic'])
        return 0
    with open(KEY_PATH, 'w') as f:
        json.dump(fresh, f, indent=1, sort_keys=True)
        f.write('\n')
    print('wrote %s (%s)' % (KEY_PATH, fresh['counts']['arithmetic']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
